[build]
  publish = "/"
  command = ""

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' blob: data:; worker-src blob:;"

[[headers]]
  for = "*.pdf"
    [headers.values]
    Content-Type = "application/pdf"
    Content-Disposition = "inline"
